env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/no-duplicate-enum-values": off
  prettier/prettier:
    - error
    - printWidth: 80
      tabWidth: 2
      singleQuote: true
      trailingComma: all
      arrowParens: always
      semi: false
      endOfLine: auto
  indent:
    - off
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/react-in-jsx-scope: off

  react/jsx-no-useless-fragment: error

  max-lines:
    - error
    - max: 400

  react/jsx-curly-brace-presence:
    - error
    - never

  prefer-const: warn
  no-unreachable: warn
