/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TutorialImport } from './routes/tutorial'
import { Route as RatingSystemImport } from './routes/rating-system'
import { Route as RankingImport } from './routes/ranking'
import { Route as AuthGuardedImport } from './routes/_auth-guarded'
import { Route as SignInIndexImport } from './routes/sign-in/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as AuthGuardedIndexImport } from './routes/_auth-guarded/index'
import { Route as UserUserIdImport } from './routes/user/$userId'
import { Route as AuthGuardedMeRouteImport } from './routes/_auth-guarded/me/route'

// Create/Update Routes

const TutorialRoute = TutorialImport.update({
  path: '/tutorial',
  getParentRoute: () => rootRoute,
} as any)

const RatingSystemRoute = RatingSystemImport.update({
  path: '/rating-system',
  getParentRoute: () => rootRoute,
} as any)

const RankingRoute = RankingImport.update({
  path: '/ranking',
  getParentRoute: () => rootRoute,
} as any)

const AuthGuardedRoute = AuthGuardedImport.update({
  id: '/_auth-guarded',
  getParentRoute: () => rootRoute,
} as any)

const SignInIndexRoute = SignInIndexImport.update({
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthGuardedIndexRoute = AuthGuardedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthGuardedRoute,
} as any)

const UserUserIdRoute = UserUserIdImport.update({
  path: '/user/$userId',
  getParentRoute: () => rootRoute,
} as any)

const AuthGuardedMeRouteRoute = AuthGuardedMeRouteImport.update({
  path: '/me',
  getParentRoute: () => AuthGuardedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-guarded': {
      id: '/_auth-guarded'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthGuardedImport
      parentRoute: typeof rootRoute
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingImport
      parentRoute: typeof rootRoute
    }
    '/rating-system': {
      id: '/rating-system'
      path: '/rating-system'
      fullPath: '/rating-system'
      preLoaderRoute: typeof RatingSystemImport
      parentRoute: typeof rootRoute
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialImport
      parentRoute: typeof rootRoute
    }
    '/_auth-guarded/me': {
      id: '/_auth-guarded/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthGuardedMeRouteImport
      parentRoute: typeof AuthGuardedImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdImport
      parentRoute: typeof rootRoute
    }
    '/_auth-guarded/': {
      id: '/_auth-guarded/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardedIndexImport
      parentRoute: typeof AuthGuardedImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthGuardedRoute: AuthGuardedRoute.addChildren({
    AuthGuardedMeRouteRoute,
    AuthGuardedIndexRoute,
  }),
  RankingRoute,
  RatingSystemRoute,
  TutorialRoute,
  UserUserIdRoute,
  RegisterIndexRoute,
  SignInIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-guarded",
        "/ranking",
        "/rating-system",
        "/tutorial",
        "/user/$userId",
        "/register/",
        "/sign-in/"
      ]
    },
    "/_auth-guarded": {
      "filePath": "_auth-guarded.tsx",
      "children": [
        "/_auth-guarded/me",
        "/_auth-guarded/"
      ]
    },
    "/ranking": {
      "filePath": "ranking.tsx"
    },
    "/rating-system": {
      "filePath": "rating-system.tsx"
    },
    "/tutorial": {
      "filePath": "tutorial.tsx"
    },
    "/_auth-guarded/me": {
      "filePath": "_auth-guarded/me/route.tsx",
      "parent": "/_auth-guarded"
    },
    "/user/$userId": {
      "filePath": "user/$userId.tsx"
    },
    "/_auth-guarded/": {
      "filePath": "_auth-guarded/index.tsx",
      "parent": "/_auth-guarded"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
