name: Lint and Build

on: [push]

jobs:
  lint-and-build:
    name: Run linter and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#     - name: Setup Node
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'

      - name: Install packages
        run: yarn && yarn lint

      - name: Run linter
        run: yarn lint

      - name: Build app
        run: yarn build