name: Lint and Build

on: [push]

jobs:
  lint-and-build:
    name: Run linter and build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Check code quality
        run: yarn lint & yarn tsc
