name: Lint and Build

on: [push]

jobs:
  lint-and-build:
    name: Run linter and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: |
          bun -v
          bun install

      - name: Run linter
        run: bun lint

      - name: Build app
        run: bun run build
