name: Lint and Build

on: [push]

jobs:
  lint-and-build:
    name: Run linter and build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Check code quality
        run: bun lint & bun tsc
